
package ru.itmo.webservices.thirdlab.standalone;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArticleWebService", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ArticleWebService {


    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param authorId
     * @param dateAdded
     * @return
     *     returns java.util.List<ru.itmo.webservices.thirdlab.standalone.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArticles", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.GetArticles")
    @ResponseWrapper(localName = "getArticlesResponse", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.GetArticlesResponse")
    @Action(input = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/getArticlesRequest", output = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/getArticlesResponse")
    public List<Article> getArticles(
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded);

    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param authorId
     * @param dateAdded
     * @return
     *     returns long
     * @throws InvalidCreatingParametersException
     * @throws InsertingException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createArticle", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.CreateArticle")
    @ResponseWrapper(localName = "createArticleResponse", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.CreateArticleResponse")
    @Action(input = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/createArticleRequest", output = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/createArticleResponse", fault = {
        @FaultAction(className = InsertingException.class, value = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/createArticle/Fault/InsertingException"),
        @FaultAction(className = InvalidCreatingParametersException.class, value = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/createArticle/Fault/InvalidCreatingParametersException")
    })
    public long createArticle(
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded)
        throws InsertingException, InvalidCreatingParametersException
    ;

    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param id
     * @param authorId
     * @param dateAdded
     * @return
     *     returns long
     * @throws IllegalIdException
     * @throws RowsNotAffectedException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateArticle", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.UpdateArticle")
    @ResponseWrapper(localName = "updateArticleResponse", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.UpdateArticleResponse")
    @Action(input = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/updateArticleRequest", output = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/updateArticleResponse", fault = {
        @FaultAction(className = IllegalIdException.class, value = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/updateArticle/Fault/IllegalIdException"),
        @FaultAction(className = RowsNotAffectedException.class, value = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/updateArticle/Fault/RowsNotAffectedException")
    })
    public long updateArticle(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded)
        throws IllegalIdException, RowsNotAffectedException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns int
     * @throws IllegalIdException
     * @throws RowsNotAffectedException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.DeleteArticle")
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://standalone.thirdlab.webservices.itmo.ru/", className = "ru.itmo.webservices.thirdlab.standalone.DeleteArticleResponse")
    @Action(input = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/deleteArticleRequest", output = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/deleteArticleResponse", fault = {
        @FaultAction(className = IllegalIdException.class, value = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/deleteArticle/Fault/IllegalIdException"),
        @FaultAction(className = RowsNotAffectedException.class, value = "http://standalone.thirdlab.webservices.itmo.ru/ArticleWebService/deleteArticle/Fault/RowsNotAffectedException")
    })
    public int deleteArticle(
        @WebParam(name = "id", targetNamespace = "")
        Long id)
        throws IllegalIdException, RowsNotAffectedException
    ;

}
