
package ru.itmo.webservices.firstlab.standalone;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArticlesService", targetNamespace = "http://standalone.firstlab.webservices.itmo.ru/", wsdlLocation = "http://localhost:8080/ArticleService?wsdl")
public class ArticlesService
    extends Service
{

    private final static URL ARTICLESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARTICLESSERVICE_EXCEPTION;
    private final static QName ARTICLESSERVICE_QNAME = new QName("http://standalone.firstlab.webservices.itmo.ru/", "ArticlesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ArticleService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARTICLESSERVICE_WSDL_LOCATION = url;
        ARTICLESSERVICE_EXCEPTION = e;
    }

    public ArticlesService() {
        super(__getWsdlLocation(), ARTICLESSERVICE_QNAME);
    }

    public ArticlesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARTICLESSERVICE_QNAME, features);
    }

    public ArticlesService(URL wsdlLocation) {
        super(wsdlLocation, ARTICLESSERVICE_QNAME);
    }

    public ArticlesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARTICLESSERVICE_QNAME, features);
    }

    public ArticlesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArticlesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ArticleWebService
     */
    @WebEndpoint(name = "ArticleWebServicePort")
    public ArticleWebService getArticleWebServicePort() {
        return super.getPort(new QName("http://standalone.firstlab.webservices.itmo.ru/", "ArticleWebServicePort"), ArticleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArticleWebService
     */
    @WebEndpoint(name = "ArticleWebServicePort")
    public ArticleWebService getArticleWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://standalone.firstlab.webservices.itmo.ru/", "ArticleWebServicePort"), ArticleWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARTICLESSERVICE_EXCEPTION!= null) {
            throw ARTICLESSERVICE_EXCEPTION;
        }
        return ARTICLESSERVICE_WSDL_LOCATION;
    }

}
