
package ru.itmo.webservices.firstlab.standalone;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArticleWebService", targetNamespace = "http://standalone.firstlab.webservices.itmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ArticleWebService {


    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param authorId
     * @param dateAdded
     * @return
     *     returns java.util.List<ru.itmo.webservices.firstlab.standalone.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArticles", targetNamespace = "http://standalone.firstlab.webservices.itmo.ru/", className = "ru.itmo.webservices.firstlab.standalone.GetArticles")
    @ResponseWrapper(localName = "getArticlesResponse", targetNamespace = "http://standalone.firstlab.webservices.itmo.ru/", className = "ru.itmo.webservices.firstlab.standalone.GetArticlesResponse")
    @Action(input = "http://standalone.firstlab.webservices.itmo.ru/ArticleWebService/getArticlesRequest", output = "http://standalone.firstlab.webservices.itmo.ru/ArticleWebService/getArticlesResponse")
    public List<Article> getArticles(
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded);

}
