
package ru.itmo.webservices.secondlab.standalone;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArticleWebService", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ArticleWebService {


    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param authorId
     * @param dateAdded
     * @return
     *     returns java.util.List<ru.itmo.webservices.secondlab.standalone.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArticles", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.GetArticles")
    @ResponseWrapper(localName = "getArticlesResponse", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.GetArticlesResponse")
    @Action(input = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/getArticlesRequest", output = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/getArticlesResponse")
    public List<Article> getArticles(
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded);

    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param authorId
     * @param dateAdded
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createArticle", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.CreateArticle")
    @ResponseWrapper(localName = "createArticleResponse", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.CreateArticleResponse")
    @Action(input = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/createArticleRequest", output = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/createArticleResponse")
    public long createArticle(
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded);

    /**
     * 
     * @param articleName
     * @param hIndex
     * @param articleDesc
     * @param id
     * @param authorId
     * @param dateAdded
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateArticle", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.UpdateArticle")
    @ResponseWrapper(localName = "updateArticleResponse", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.UpdateArticleResponse")
    @Action(input = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/updateArticleRequest", output = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/updateArticleResponse")
    public long updateArticle(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "authorId", targetNamespace = "")
        String authorId,
        @WebParam(name = "hIndex", targetNamespace = "")
        Long hIndex,
        @WebParam(name = "articleName", targetNamespace = "")
        String articleName,
        @WebParam(name = "articleDesc", targetNamespace = "")
        String articleDesc,
        @WebParam(name = "dateAdded", targetNamespace = "")
        Long dateAdded);

    /**
     * 
     * @param id
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.DeleteArticle")
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://standalone.secondlab.webservices.itmo.ru/", className = "ru.itmo.webservices.secondlab.standalone.DeleteArticleResponse")
    @Action(input = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/deleteArticleRequest", output = "http://standalone.secondlab.webservices.itmo.ru/ArticleWebService/deleteArticleResponse")
    public int deleteArticle(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
